# Generated by Django 5.2.3 on 2026-02-27 15:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=12)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('bill_to_name', models.CharField(max_length=255)),
                ('bill_to_company', models.CharField(blank=True, max_length=255)),
                ('bill_to_email', models.EmailField(blank=True, max_length=254)),
                ('bill_to_phone', models.CharField(blank=True, max_length=50)),
                ('bill_to_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, max_length=60)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
