# Generated by Django 5.2.3 on 2026-02-27 18:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_generate_invoices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='applied_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_to_invoices', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='coverage_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='months_covered',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
